version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"  # Uncomment this if you want to map a local port to the container
    volumes:
      - ./app:/app  # Correct indentation and ensure the path is relative
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    # expose:
    #   - "80"  # Expose expects a simple list of ports
