---
name: Checks
# just name the yml

# which action it should trigger exp pull request
on: [push]

# define the jobs
# name is for jobs and run on ubunti

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
    #   - name: Install Docker Compose (Latest)
    #     run: |
    #       sudo apt-get update
    #       sudo apt-get install -y docker-compose
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
